#MOFUCRAFT!!! Flight


#1分あたりの価格
price1: 500
#1~10分

price2: 300
#11~30分(割引有)

price3: 200
#31~(割引有)

max-player: 15
type: "mspt"
max-tps: 17.0
min-mspt: 60
min-kick-time: 20
#minutes

#the function to set the prefix
set-time: