#AFK
#
#the function to kick automatically
#max-player: how many players
#type: tps or mspt
#max-tps:
#min-mspt:

#seconds
set-afk-interval: 5
#minutes

max-player: 15
type: "mspt"
max-tps: 17.0
min-mspt: 60
min-kick-time: 20
#minutes

#the function to set the prefix
set-time: